codecov:
  notify:
    require_ci_to_pass: no
comment:
  layout: 'header, changes, diff, files'
  behavior: default
coverage:
  status:
    patch:
      default:
        target: 90%
    project:
      default:
        target: auto
        threshold: 1%
ignore:
  - src/instrumentatios/static-instrumentations/grpc-js/
  - src/instrumentatios/extentions/aws/
