version: '2'
services:
  test-server:
    build:
      dockerfile: Dockerfile
      context: ./server
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4317
      - MONGO_URL=mongodb://mongo_server:27017
    ports:
      - '7080:7080'
