version: '2'
services:
  test-server:
    build:
      context:  ../
      dockerfile: system-tests/server/Dockerfile
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4317
    ports:
      - '7080:7080'
    depends_on:
    - test-collector

  test-collector:
    build:
      context: ../
      dockerfile: system-tests/test-collector/Dockerfile
    ports:
      - '11337:11337'
