version: '2'
services:
  test-server:
    build:
      context:  ../../
      dockerfile: system-tests/server/Dockerfile
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4317
      - MONGO_URL=mongodb://mongo_server:27017
    ports:
      - '7080:7080'
