receivers:
  otlp:
    protocols:
      grpc:

exporters:
  logging:

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]
