receivers:
  otlp:
    protocols:
      grpc:

exporters:
  file:
    ./test_spans.json
  logging:

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, file]
