  name: Continuous Integration
  on:
    pull_request:
    push:
      branches:
        - main
  permissions: read-all
  jobs:
    unit-test:
      # strategy:
      #   fail-fast: false
      #   matrix:
      #     container: [ "node:10", "node:12", "node:14" ]
      runs-on: ubuntu-latest
      services:
        redis:
          image: redis
          # ports:
          # - 6379:6379
          options: >-
            --health-cmd "redis-cli ping"
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5
      env:
          RUN_REDIS_TEST: 1
      container: node:10.18-jessie
      # container:
      #   image: ${{ matrix.container }}
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Cache Dependencies
          uses: actions/cache@v2
          with:
            path: |
              node_modules
              package-lock.json
            key: ${{ runner.os }}-${{ matrix.container }}-${{ hashFiles('**/package.json') }}
        - name: Install Root Dependencies
          run: npm install --ignore-scripts
        - name: Install dependencies
          run: npm ci
        - name: build
          run: npm run build
        - name: Unit tests
          run: npm run test
        - name: Coverage
          if: matrix.container == 'node:14'
          run: npm run codecov
